# Guardrail GitHub Actions Workflow
# Copy this file to .github/workflows/guardrail.yml

name: Guardrail

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  guardrail:
    name: Code Verification
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      security-events: write  # For SARIF upload
      pull-requests: write    # For PR comments
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better analysis

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Guardrail Scan
        run: npx guardrail scan --format=json,html,sarif
        continue-on-error: true

      - name: Guardrail Gate
        id: gate
        run: npx guardrail gate --threshold=80
        continue-on-error: true

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: .guardrail/results.sarif

      - name: Upload Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: guardrail-report
          path: .guardrail/
          retention-days: 30

      - name: Check Gate Result
        if: steps.gate.outcome == 'failure'
        run: |
          echo "::error::Guardrail gate failed. Check the report for details."
          exit 1
